FROM node:20 AS build-stage
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy project files
COPY . .

RUN npm run build
# Runtime stage
FROM node:20
WORKDIR /app
RUN npm install -g serve

COPY --from=build-stage /app/dist ./dist
# COPY --from=build-stage /app/.env.template ./.env.template    

# Copy the entrypoint script
# COPY docker-entrypoint.sh /docker-entrypoint.sh
#RUN chmod +x /docker-entrypoint.sh
EXPOSE 8080
ENV NODE_ENV=production

COPY docker-entrypoint.sh .
RUN chmod +x docker-entrypoint.sh
SHELL ["/bin/bash", "-c"]
CMD ["/bin/bash", "./docker-entrypoint.sh"]
#CMD ["serve", "-s", "dist", "-l", "8080"]

#COPY package*.json ./
#RUN npm install
#RUN npx update-browserslist-db@latest

#RUN npm run lint --fix || true
# RUN npm run build

# Generated by Copilot: Runtime stage with serve
#FROM node:22 AS runtime-stage
#WORKDIR /app

# Install serve globally
#RUN npm install -g serve

# Copy built files and startup script



#EXPOSE 8080
#ENV NODE_ENV=production
#ENV HOST=0.0.0.0
#ENV PORT=8080

#CMD ["/docker-entrypoint.sh"]